application: our-episode-111216
module: billing-export
version: test
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /loader.gif
  static_files: loader.gif
  upload: loader.gif
- url: /index.html
  static_files: index.html
  upload: index.html
  login: admin
- url: /
  static_files: index.html
  upload: index.html
  login: admin
- url: /chart.js
  static_files: chart.js
  upload: chart.js
- url: /billing_export.css
  static_files: billing_export.css
  upload: billing_export.css
- url: /bootflat.css
  static_files: bootflat.css
  upload: bootflat.css
- url: /objectChangeNofication
  script: main.app
- url: /.*
  login: admin
  script: main.app

libraries:
- name: pycrypto
  version: "latest"
- name: jinja2
  version: "latest"

builtins:
- remote_api: on
- deferred: on
